version: '3.8'

services:
  dual-arm:
    image: test_ur:latest
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ~/Documents/AAU/Semester5/P5/P5-Dual-Arm:/home/P5-Dual-Arm
    user: "1000:1000"
    stdin_open: true  # equivalent to -it
    tty: true         # equivalent to -it

