version: '3.8'

services:
  dual-arm:
    image: p5_dual_arm:latest
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev/dri/:/dev/dri
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../P5-Dual-Arm:/home/P5-Dual-Arm
    user: "1000:1000"
    stdin_open: true  # equivalent to -it
    tty: true         # equivalent to -it

