kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.16247709577808281
    roll: -0
    pitch: 0
    yaw: -2.9216796186223599e-08
  upper_arm:
    x: 4.8347537932840372e-05
    y: 0
    z: 0
    roll: 1.5711559306193343
    pitch: 0
    yaw: 3.1542978294003684e-06
  forearm:
    x: -0.42484450445894556
    y: 0
    z: 0
    roll: 4.1362483499664989e-05
    pitch: -0.0010966730691664606
    yaw: 6.2615783606348882e-06
  wrist_1:
    x: -0.3922704872367892
    y: -0.00086124840267641197
    z: 0.13318112653585382
    roll: 0.0064666549977683476
    pitch: 9.311334179394734e-05
    yaw: -1.0950866442805259e-05
  wrist_2:
    x: 0.00021897761426275936
    y: -0.099489119247902214
    z: 0.00013251828334189615
    roll: 1.5694643398804196
    pitch: 0
    yaw: -8.9468104218226596e-07
  wrist_3:
    x: 1.7131173569704747e-05
    y: 0.099379763322379286
    z: 2.185672864786343e-05
    roll: 1.5710162581729232
    pitch: 3.1415926535897931
    yaw: -3.1415924903168353
  hash: calib_16261192365555346323